### ISSUE TITLE
Can not open dir content on treemap view

### ISSUE THREAD

**Issue by Lumenath** [jdvillal/systats-rs#8]
It seems like the directory tree next to the treemap in storage device details does not allow to go deeper than 3 levels in the tree.

I found that this is hard coded in the function where the treemap is created, I just don't know if ithis is intentional.

**Comment by jdvillal** [comment]
I wouldn't call this an issue, but rather a limitation. Its done that way because scanning the entire content of a disk drive can take a LOT of time depending of the content of the drive.  I found a crate that recursively path the tree usgin parallelism, the plan is to use that and then cache the tree so the device is not scanned from start everytime the user open that view.
